# Generated by Django 5.0.4 on 2024-04-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(verbose_name='Data Registro')),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Medido')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.location', verbose_name='Localização')),
            ],
        ),
    ]
