# Generated by Django 5.0.4 on 2024-04-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da Locação', max_length=60, verbose_name='Nome')),
                ('threshold', models.IntegerField(default=50, help_text='Limite Aceitável', verbose_name='Limite')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='Unidade Organização')),
            ],
        ),
    ]
